# Generated by Django 4.0.5 on 2022-07-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('age', models.IntegerField(default=0)),
                ('phyicalhealth', models.CharField(max_length=15)),
                ('insulin', models.CharField(max_length=15)),
                ('BMI', models.IntegerField(default=0)),
                ('Bloodpressure', models.CharField(max_length=15)),
                ('eyedamage', models.CharField(max_length=15)),
                ('Glucose', models.CharField(max_length=15)),
                ('retinopathy', models.CharField(max_length=15)),
            ],
        ),
    ]
