# Generated by Django 4.0.6 on 2022-07-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='gender',
            field=models.IntegerField(choices=[('Male', 'Male'), ('Female', 'Female')]),
        ),
    ]
